version: "3.8"

services:
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: clothes_shop
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ChangeMe
      POSTGRES_USER: symfony
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'

  #  redis:
  #    image: redis:latest
  #    ports:
  #      - 6379:6379

  php-fpm:
    container_name: php-fpm
    build:
      context: ""
      dockerfile: php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    environment:
      PHP_IDE_CONFIG: "serverName=SymfonyDocker"
    volumes:
      - ./../:/var/www/
    depends_on:
      - 'database'

  nginx:
    container_name: nginx
    build:
      context: nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm

volumes:
  db-data: